# Generated by Django 5.2.13 on 2026-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria_principal',
            field=models.CharField(choices=[('hidratante', 'Hidratante'), ('exfoliante', 'Exfoliante'), ('antioxidante', 'Antioxidante'), ('calmante', 'Calmante'), ('seborregulador', 'Control de Sebo'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
