# Generated by Django 5.2.13 on 2026-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_ingrediente_categoria_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('limpiador', 'Limpiador'), ('tonico', 'Tónico'), ('escencia', 'Escencia'), ('serum', 'Serum'), ('crema', 'Crema Hidratante'), ('protector', 'Protector Solar'), ('mascarilla', 'Mascarilla'), ('tratamiento', 'Tratamiento Específico'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
