# Generated by Django 5.2.13 on 2026-04-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_producto_imagen_producto_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hidratacion_actual',
            field=models.IntegerField(default=84),
        ),
        migrations.AddField(
            model_name='usuario',
            name='preocupaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='racha_dias',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('limpiador', 'Limpiador'), ('tonico', 'Tónico'), ('escencia', 'Escencia'), ('serum', 'Serum'), ('hidratante', 'Hidratante'), ('protector', 'Protector Solar'), ('mascarilla', 'Mascarilla'), ('tratamiento', 'Tratamiento Específico'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='rutinas', to='skincare.producto'),
        ),
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('AM', 'Mañana (AM)'), ('PM', 'Noche (PM)')], default='AM', max_length=2)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skincare.producto')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='skincare.rutina')),
            ],
            options={
                'ordering': ['momento', 'orden'],
            },
        ),
    ]
